using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CybsClass.Cybersource.Models
{
    public enum FollowOnTransactions
    {
        AUTH,
        SALE,
        CAPTURE,
        REVERSAL,
        VOID_SALE,
        VOID_CAPTURE,
        VOID_CREDIT,
        VOID_REFUND,
        REFUND_SALE,
        REFUND_CAPTURE,
        CREDIT,
        TOKEN_CREATE,
        INST_ID_CREATE,
        INST_ID_DELETE,
        INST_ID_UPDATE,
        INST_ID_RETRIEVE,
        PAY_ID_CREATE,
        PAY_ID_DELETE,
        PAY_ID_UPDATE,
        PAY_ID_RETRIEVE,
        CUST_ID_CREATE,
        CUST_ID_DELETE,
        CUST_ID_UPDATE,
        CUST_ID_RETRIEVE,
        TOKEN_DECRYPT,
        SHIPPING_ID_CREATE,
        SHIPPING_ID_DELETE,
        SHIPPING_ID_UPDATE,
        SHIPPING_ID_RETRIEVE,
        UNIFIED_CHECKOUT,
        UNIFIED_CHECKOUT_PAYMENT,
        INVOICE_CREATE,
        PA_SETUP,
        PA_ENROLL,
        PA_VALIDATE,
        MERCHANT_BOARDING_CREATE,
        TRANSACTION_BOARDING_CREATE,
        SEMI_POS_SETUP,
        SEMI_POS_SALE,
        SEMI_POS_PRE_AUTH,
        SEMI_POS_STATUS_CHECK,
        SEMI_POS_STANDALONE_RETURN,
        SEMI_POS_CANCEL,
        SEMI_POS_TOKEN_RETURN,
        SEMI_POS_CAPTURE,
        CLOUD_POS_BEARER_CREATE,
        CLOUD_POS_BEARER_SALE,
        CLOUD_POS_BEARER_PRE_AUTH,
        CLOUD_POS_BEARER_STATUS_CHECK,
        CLOUD_POS_BEARER_STANDALONE_RETURN,
        CLOUD_POS_CANCEL,
        CLOUD_POS_CAPTURE,
        SIMPLE_STRING,
        STANDALONE_AFT_TRANSACTION,
        TOKEN_AFT_TRANSACTION,
        FLEX_AFT_TRANSACTION,
        FLEX_PA_SETUP,
        FLEX_AFT_CHECK_ENROLL_AUTH,
    }
}
